name: connectcare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  mysql1: ^0.20.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  image: ^4.3.0
  shared_preferences: ^2.3.2
  firebase_auth: ^5.3.1
  nfc_manager: ^3.5.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.6.0
  logger: ^2.4.0
  flutter_facebook_auth: ^7.1.1
  convex_bottom_bar: ^3.2.0
  table_calendar: ^3.0.9
  intl: ^0.19.0
  country_code_picker: ^3.1.0
  firebase_app_check: ^0.3.1+6
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.7
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ConnectCareLogo.webp"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/en.json
    - assets/translations/es.json

  fonts:
    - family: Suisse_Intl
      fonts:
        - asset: assets/fonts/fonnts.com-Suisse_Intl_Bold.ttf
          weight: 700
        - asset: assets/fonts/fonnts.com-Suisse_Intl_Medium.ttf
          weight: 500
        - asset: assets/fonts/fonnts.com-Suisse_Intl_Regular.ttf
          weight: 400
        - asset: assets/fonts/fonnts.com-SuisseIntl-Light.ttf
          weight: 300
