// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMl2OmwksVaFykUhMevrc39XpQV2BNahE',
    appId: '1:1061884124346:web:ba94549d07dd952892f683',
    messagingSenderId: '1061884124346',
    projectId: 'connectcare-8576a',
    authDomain: 'connectcare-8576a.firebaseapp.com',
    storageBucket: 'connectcare-8576a.firebasestorage.app',
    measurementId: 'G-PCXETTZKTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFLKf4Uqbn2rkE_D0QeyGjxvor8g15zPo',
    appId: '1:1061884124346:android:48612fee86203d2792f683',
    messagingSenderId: '1061884124346',
    projectId: 'connectcare-8576a',
    storageBucket: 'connectcare-8576a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApXwlqjV5GgtchjNQZko9ivco4I56aPzY',
    appId: '1:1061884124346:ios:e1778e1eceb7750b92f683',
    messagingSenderId: '1061884124346',
    projectId: 'connectcare-8576a',
    storageBucket: 'connectcare-8576a.firebasestorage.app',
    androidClientId: '1061884124346-66n0pl4jav730t5vje31uda56ipjk2oi.apps.googleusercontent.com',
    iosClientId: '1061884124346-p0fsadlka2s6jklv6vnc655vq52ae2f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApXwlqjV5GgtchjNQZko9ivco4I56aPzY',
    appId: '1:1061884124346:ios:e1778e1eceb7750b92f683',
    messagingSenderId: '1061884124346',
    projectId: 'connectcare-8576a',
    storageBucket: 'connectcare-8576a.appspot.com',
    androidClientId: '1061884124346-77r5e60o55825ups9cgudphm8tm7fvtt.apps.googleusercontent.com',
    iosClientId: '1061884124346-p0fsadlka2s6jklv6vnc655vq52ae2f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMl2OmwksVaFykUhMevrc39XpQV2BNahE',
    appId: '1:1061884124346:web:cc240ed6ebc401a392f683',
    messagingSenderId: '1061884124346',
    projectId: 'connectcare-8576a',
    authDomain: 'connectcare-8576a.firebaseapp.com',
    storageBucket: 'connectcare-8576a.appspot.com',
    measurementId: 'G-HGF8NFEWJH',
  );
}